site_name: xpektra
site_description: The documentation for xpektra software package
site_author: Mohit Pundir

repo_url: https://github.com/smec-ethz/xpektra
repo_name: smec-ethz/xpektra

copyright: Copyright &copy; 2026 ETH Zurich (SMEC)

theme:
  name: material
  features:
    - navigation.instant # Instant navigation between pages
    - navigation.tabs # Show section headers in the navigation sidebar
    - header-autohide # header disappears when scrolling down
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - search.highlight
    - search.suggest
    - content.footnote.tooltips

  palette:
    - scheme: default
      primary: white
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  favicon: "assets/favicon-xpektra.png"
  logo: "assets/favicon-xpektra.png"
  icon:
    repo: fontawesome/brands/github # GitHub logo in top right

extra_javascript:
  # The below two make MathJax work, see https://squidfunk.github.io/mkdocs-material/reference/mathjax/
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/vtk.js
  - https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.js
  - javascripts/carousel.js

extra_css:
  - https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200
  - "stylesheets/custom_css.css"
  - https://cdn.jsdelivr.net/npm/swiper@11/swiper-bundle.min.css
  - "stylesheets/mkdocstrings.css"
  - "stylesheets/extra.css"
  - "stylesheets/carousel.css"

markdown_extensions:
  - pymdownx.arithmatex: # Render LaTeX via MathJax
      generic: true
  - pymdownx.superfences # Seems to enable syntax highlighting when used with the Material theme.
  - pymdownx.details # Allowing hidden expandable regions denoted by ???
  - pymdownx.snippets: # Include one Markdown file into another
      base_path: docs
  - admonition
  - toc:
      permalink: "¤" # Adds a clickable permalink to each section heading
      toc_depth: 4

plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
  - autorefs
  - section-index
  - mkdocstrings:
      handlers:
        python:
          paths: [tatva]
          options:
            backlinks: tree
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: list
            filters: ["!^_"]
            force_inspection: true
            heading_level: 3
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            separate_signature: true
            members_order: source
            show_bases: false
            show_if_no_docstring: true
            show_overloads: false
            show_root_heading: true
            show_signature_annotations: true
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            summary: true
  - ipynb:

nav:
  - Home: "index.md"
  - Getting Started:
      - "getting_started.md"
  - Basics of xpektra:
      - Building Blocks: "basics.md"
      - "extensibility.md"
  - Examples:
      - Fourier-Galerkin:
          - "examples/linear_elasticity.ipynb"
          - "examples/st_venant_kirchhoff.ipynb"
          - "examples/j2_plasticity.ipynb"
          - "examples/multiphase_material.ipynb"
      - Moulinec-Suquet:
          - "examples/moulinec_suquet.ipynb"
          - "examples/moulinec_suquet_newton_krylov.ipynb"
      - Displacement-based FFT:
          - "examples/displacement_based_fft.ipynb"
      - "examples/differential_operator.ipynb"
      - "examples/phasefield_localization_1D.ipynb"
      - "examples/computational_homogenization.ipynb"
      - "examples/multiscale.ipynb"
  - API Reference:
      - "api/projection_operators.md"
      - "api/scheme_api.md"
      - "api/spectral_operator_api.md"
      - "api/spectral_space_api.md"
